### ISSUE TITLE
ability to "git pull" + "docker build" instead of just "docker pull" for a job

### ISSUE THREAD

**Issue by tianon** [paultag/moxie#40]
It'd be great to hand a job a Git repo path and have it do `git pull` and then `docker build` directly instead of having to wait for either Hub automated builds or pushes from my local box in order to deploy.

**Comment by paultag** [comment]
:+1:

**Comment by tianon** [comment]
As one possible implementation, this _could_ just be a custom "pre-script" and a way to disable image pulling (and then my pre-script could just build the image name my job is about to run).

**Comment by tianon** [comment]
ie:
```yaml
pre-script:
  - cd /path/to/git && git pull
  - docker build -t my-image /path/to/git
image: "my-image"
```
